defaults: &defaults
  link_take: "http://maps.google.com/maps?ie=UTF8&hl=en&view=map&cid=12018039332956938942&q=Restaurante+Tak%C3%AA&ved=0CB0QpQY&ei=6Qk1S8zDMZm6ywTZoOW9Bw&hq=Restaurante+Tak%C3%AA&hnear=&z=16&iwloc=A"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

