# APP Global settings
common: &common
  name: Testadores
  support_email: testadores_ouvidoria@yahoogrupos.com.br
  noreply_email: nao-responda@testadores.com.br

development:
  <<: *common
  domain: localhost:3000

test:
  <<: *common
  domain: localhost:3000

production:
  <<: *common
  domain: testadores.com.br
